//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularProject.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTBL
    {
        public int logID { get; set; }
        public int userID { get; set; }
        public string logActivity { get; set; }
        public System.DateTime logDate { get; set; }
        public string ipAddress { get; set; }
        public string logUsername { get; set; }
        public bool isDelete { get; set; }
    
        public virtual UserTBL UserTBL { get; set; }
    }
}
