//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularProject.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTBL
    {
        public int orderID { get; set; }
        public int userID { get; set; }
        public double totalAmount { get; set; }
        public System.DateTime orderDate { get; set; }
        public string orderStatus { get; set; }
        public bool isDelete { get; set; }
        public string address { get; set; }
        public int phoneNumber { get; set; }
        public int productID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> unitPrice { get; set; }
    
        public virtual UserTBL UserTBL { get; set; }
    }
}
