//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularProject.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTBL
    {
        public int detailID { get; set; }
        public int orderID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public decimal unitPrice { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual OrderTBL OrderTBL { get; set; }
        public virtual ProductTBL ProductTBL { get; set; }
    }
}
