//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularProject.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTBL()
        {
            this.OrderDetailTBL = new HashSet<OrderDetailTBL>();
            this.ShoppingCartTBL = new HashSet<ShoppingCartTBL>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public decimal price { get; set; }
        public int stockQuantity { get; set; }
        public int categoryID { get; set; }
        public string imageURL { get; set; }
        public bool isDelete { get; set; }
    
        public virtual CategoryTBL CategoryTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTBL> OrderDetailTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartTBL> ShoppingCartTBL { get; set; }
    }
}
