//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularProject.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartTBL
    {
        public int cartID { get; set; }
        public int userID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual ProductTBL ProductTBL { get; set; }
        public virtual UserTBL UserTBL { get; set; }
    }
}
